apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: a-python-library
    description: A Python Library
    annotations:
        backstage.io/techdocs-ref: dir:.
    tags:
        - python
    links:
        - url: https://admin.example-org.com
          title: Admin Dashboard
          icon: dashboard
          type: admin-dashboard
spec:
    type: service
    lifecycle: production
    owner: team-a
    system: project-x
